### ISSUE TITLE
Wrong IP Address in Request 

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSVisualisierung#3]
Ehr Base Server, SmICS Core + SmICS Visualisierung are installed on the same Linux Server and start the software in Browser from my own Laptop, no Patient Data is showed when I entered the right Patient ID and period. The following error is found in Chrome:

There was en error executing the procedure [code: 2]: FetchError: request to http://localhost:9787/api/StoredProcedures/Patient_Bewegung_Ps failed, reason: connect ECONNREFUSED 127.0.0.1:9787

![SMICS 0 8 - Google Chrome Di, 06 04 21 17_31_47 (2)](https://user-images.githubusercontent.com/79518032/113737152-10a46180-96fe-11eb-94a8-9a5e9bdd14c6.png)

**Comment by dagmarkrefting** [comment]
this is due to hardcoding of localhost in  line 55 of 

https://github.com/highmed/SmICSVisualisierung/blob/master/src/server/config.ts 

if you go through the full npm build Process, or

https://github.com/highmed/SmICSVisualisierung/blob/master/build/server/config.js

if you take the shortcut to build directly the docker containers.

The name needs to match the dotnet-containername in https://github.com/highmed/SmICSCore/blob/develop/docker-compose.yml

So you need to replace `localhost` by `smics_core`

and rebuild 




or

**Comment by ZhuYufei990** [comment]
Since the request is sended in Javascript from the user's browser, we need to set the IP-Adresse of the Server in config.

**Comment by ZhuYufei990** [comment]
Another tipps to make our life simpler: Do NOT install SmICS and Ehr Base on the same Server! SmICS Core and Visualisierung should be on the same Server, but Ehr base should run on another server. Don't ask why I know that.
